const DATA = {
  rooms: [
    {
      buildingName: "EITC",
      roomNumber: "105",
      roomImage: "",
      roomDescription: "Projector/TV_Whiteboard_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Available" },
        { time: 10, status: "Available" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Available" },
        { time: 3, status: "Available" },
        { time: 4, status: "Available" },
        { time: 5, status: "Chess Club" },
        { time: 6, status: "Chess Club" },
      ],
    },
    {
      buildingName: "EITC",
      roomNumber: "215",
      roomImage: "",
      roomDescription: "Projector/TV_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Available" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Available" },
        { time: 3, status: "Available" },
        { time: 4, status: "Available" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "EITC",
      roomNumber: "220",
      roomImage: "",
      roomDescription: "Projector/TV_Whiteboard_Ritual Circle",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Lecture" },
        { time: 4, status: "Lecture" },
        { time: 5, status: "D&D" },
        { time: 6, status: "D&D" },
      ],
    },
    {
      buildingName: "EITC",
      roomNumber: "320",
      roomImage: "",
      roomDescription: "Whiteboard_Moveable Tables_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Meeting" },
        { time: 3, status: "Available" },
        { time: 4, status: "Available" },
        { time: 5, status: "Study Group" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "Drake Centre",
      roomNumber: "104",
      roomImage: "",
      roomDescription: "Projector/TV",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Available" },
        { time: 10, status: "Available" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Dragon Taming" },
        { time: 4, status: "Available" },
        { time: 5, status: "Available" },
        { time: 6, status: "Pillow Fort Competition" },
      ],
    },
    {
      buildingName: "Drake Centre",
      roomNumber: "112",
      roomImage: "",
      roomDescription:
        "Projector/TV_Whiteboard_Moveable Tables_Food Allowed_Ritual Circle",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Board Games" },
        { time: 4, status: "Board Games" },
        { time: 5, status: "Board Games" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "Drake Centre",
      roomNumber: "128",
      roomImage: "",
      roomDescription: "Projector/TV_Whiteboard_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Study Group" },
        { time: 12, status: "Study Group" },
        { time: 1, status: "Study Group" },
        { time: 2, status: "Lecture" },
        { time: 3, status: "Lecture" },
        { time: 4, status: "Lecture" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "Drake Centre",
      roomNumber: "310",
      roomImage: "",
      roomDescription: "Whiteboard_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Lecture" },
        { time: 3, status: "Lecture" },
        { time: 4, status: "Lecture" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "Isbister Building",
      roomNumber: "103",
      roomImage: "",
      roomDescription: "Whiteboard_Moveable Tables_Food Allowed",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Meeting" },
        { time: 10, status: "Available" },
        { time: 11, status: "Available" },
        { time: 12, status: "Available" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Nap Time" },
        { time: 4, status: "Nap Time" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "Isbister Building",
      roomNumber: "107",
      roomImage: "",
      roomDescription: "Whiteboard_Moveable Tables",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Study Group" },
        { time: 10, status: "Available" },
        { time: 11, status: "Available" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Lecture" },
        { time: 4, status: "Lecture" },
        { time: 5, status: "Bowling" },
        { time: 6, status: "Bowling" },
      ],
    },
    {
      buildingName: "Isbister Building",
      roomNumber: "207",
      roomImage: "",
      roomDescription: "Projector/TV_Moveable Tables_Food Allowed",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Available" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Dance Party" },
        { time: 3, status: "Available" },
        { time: 4, status: "Lecture" },
        { time: 5, status: "Available" },
        { time: 6, status: "Fingerboarding Finals" },
      ],
    },
    {
      buildingName: "Isbister Building",
      roomNumber: "307",
      roomImage: "",
      roomDescription: "Whiteboard_Food Allowed_Ritual Circle",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Available" },
        { time: 10, status: "Meeting" },
        { time: 11, status: "Available" },
        { time: 12, status: "Available" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Lecture" },
        { time: 3, status: "Lecture" },
        { time: 4, status: "Available" },
        { time: 5, status: "LAN Party" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "University College",
      roomNumber: "302",
      roomImage: "",
      roomDescription: "Projector/TV_Whiteboard_Moveable Tables_Food Allowed",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Available" },
        { time: 12, status: "Available" },
        { time: 1, status: "Lecture" },
        { time: 2, status: "Lecture" },
        { time: 3, status: "Available" },
        { time: 4, status: "Available" },
        { time: 5, status: "Lecture" },
        { time: 6, status: "Lecture" },
      ],
    },
    {
      buildingName: "University College",
      roomNumber: "305",
      roomImage: "",
      roomDescription: "Whiteboard_Moveable Tables_Food Allowed",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Available" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Lecture" },
        { time: 12, status: "Lecture" },
        { time: 1, status: "Available" },
        { time: 2, status: "Available" },
        { time: 3, status: "Potluck" },
        { time: 4, status: "Available" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "University College",
      roomNumber: "306",
      roomImage: "",
      roomDescription: "Whiteboard_Food Allowed",
      occupied: false,
      scheduleData: [
        { time: 9, status: "Lecture" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Available" },
        { time: 12, status: "Available" },
        { time: 1, status: "Available" },
        { time: 2, status: "D&D" },
        { time: 3, status: "D&D" },
        { time: 4, status: "D&D" },
        { time: 5, status: "Available" },
        { time: 6, status: "Available" },
      ],
    },
    {
      buildingName: "University College",
      roomNumber: "310",
      roomImage: "",
      roomDescription: "Ritual Circle",
      occupied: true,
      scheduleData: [
        { time: 9, status: "Available" },
        { time: 10, status: "Lecture" },
        { time: 11, status: "Available" },
        { time: 12, status: "Available" },
        { time: 1, status: "Arts and Crafts" },
        { time: 2, status: "Available" },
        { time: 3, status: "Available" },
        { time: 4, status: "Available" },
        { time: 5, status: "Seance" },
        { time: 6, status: "Exorcism" },
      ],
    },
  ],
};
